### ISSUE TITLE
Using Databases with Render

### ISSUE THREAD

**Issue by Stelluuh** [learn-co-curriculum/phase-4-using-databases-with-render#2]
### Canvas Link

https://learning.flatironschool.com/courses/5303/pages/using-databases-with-render?module_item_id=502433

### Concern

I can't participate in this canvas lecture because limited free tier databases in Render. When following the steps for Creating a PostgreSQL Instance section, I get an error:
Error: cannot have more than one active free tier database

There are no instructions on whether this is supposed to happen or if I should somehow deactivate the previous database in the last lecture. Although it seems like we need it for the next part of this section.

**Comment by lizbur10** [comment]
Hi @Stelluuh! It's true that Render only lets you have one PostgreSQL instance, but you can create multiple databases within that one instance. See the "Creating Multiple Databases within a PostgreSQL Instance" section of the lesson for instructions on how to do that.

Hope this helps!
